[http]
# Http Server Settings
PORT=8080
HTTP_HOST="127.0.0.1"


[ai]
# Epsillon greedy parameter
EPS_GREED=0.2


[env]
# Maximum agent health
MAX_HEALTH=100
# Maximum agent hunger
MAX_HUNGER=100

# Minimum vision
MIN_VISION=1
# Maximum vision
MAX_VISION=30

# Initial population number
INIT_POPULATION=30

# Minimum lifespan amount (steps) - from range
MIN_LIFESPAN_RND=50
# Maximum lifespan amount (steps) - to range
MAX_LIFESPAN_RND=100

# Male gender probability to create agent
MALE_GENDER_PROB=0.5

# Hitting wall damage
HIT_WALL_DAMAGE=0.5
# Amount of energy takes to walk each step
WALKING_HUNGER=1

# Probability of die when lifespan finished (Otherwise agent get damage each step)
KILL_END_LIFE_THRESH=0.25
# Eldery damage (When lifespan is done but didn't died)
ELD_DAMAGE=5

# Agent takes damage if hungrier than this threshold
UNHEALTHY_HUNGER=20
# Damage on unhealthy hugner
UNHEALTHY_HUNGER_DAMAGE=0.2

# ** Heal from good diet (good hunger):
# If health is less than:
GOOD_DIET_HEAL_HEALTH_LESS=80
# And hunger is more than:
GOOD_DIET_HEAL_HUNGER_MORE=90
# Then heal this amount:
GOOD_DIET_HEAL_AMOUNT=5
# And get hungrier this amount:
GOOD_DIET_HEAL_HUNGRY_AMOUNT=5

# Heal after eat food
HEAL_AFTER_EAT=5
# Raise hunger after eat food
HUNGER_AFTER_FOOD=5

# Food generate chance in each step
FOOD_GENERATE=0.5
# Min food generate
FOOD_MIN=1
# Min food generate
FOOD_MAX=5


[sex]
# ** Sex logic:
# If hunger was less than below amount:
SEX_HORNY_HUNGER=20
# Getting horny by this probability:
SEX_HORNY_HUNGER_HORNY=1
# Else get horny by this probability:
SEX_HORNINESS=0.8

# If parents health add up to:
SEX_PARENT_HEALTH_SUM=100
# And parent hunger add up to:
SEX_PARENT_HUNGER_SUM=100
# There is this chance to give birth min of:
SEX_PARENT_HEALTHY_BABY_MIN=1
# And max of:
SEX_PARENT_HEALTHY_BABY_MAX=5
# If parents where weak there is this chance to give birth to a dead baby:
SEX_PARENT_UNHEALTHY_DIED_BABY=0.5

# Cant do a new sex after sex for n steps:
SEX_HALT_STEPS=2

# Minimum health required to sex
SEX_MIN_HEALTH=20

# Distance to find a mate
MATE_DISTANCE=1

# Getting hungry after normal sex
SEX_NORM_HUNGRY=2

# Damage to famale after gave birth
SEX_FEMALE_DAMAGE=2

# Hunger after mastribation
SEX_MASTR_HUNGER=2
